//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BonfieFood.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BonfieFood.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1_one {
            get {
                object obj = ResourceManager.GetObject("_1_one", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2_two {
            get {
                object obj = ResourceManager.GetObject("_2_two", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3_three {
            get {
                object obj = ResourceManager.GetObject("_3_three", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4_four {
            get {
                object obj = ResourceManager.GetObject("_4_four", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5_five {
            get {
                object obj = ResourceManager.GetObject("_5_five", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6_six {
            get {
                object obj = ResourceManager.GetObject("_6_six", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap added_nutrition {
            get {
                object obj = ResourceManager.GetObject("added_nutrition", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap B_logo_2 {
            get {
                object obj = ResourceManager.GetObject("B_logo_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background_login {
            get {
                object obj = ResourceManager.GetObject("background_login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bonfie {
            get {
                object obj = ResourceManager.GetObject("bonfie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyse photo.
        /// </summary>
        internal static string btn_ScanPhoto {
            get {
                return ResourceManager.GetString("btn_ScanPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string btnAddNutrition {
            get {
                return ResourceManager.GetString("btnAddNutrition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string btnProducts {
            get {
                return ResourceManager.GetString("btnProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes.
        /// </summary>
        internal static string btnRecipes {
            get {
                return ResourceManager.GetString("btnRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnSavePerInfo {
            get {
                return ResourceManager.GetString("btnSavePerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string btnViewGoals {
            get {
                return ResourceManager.GetString("btnViewGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string btnViewSavedRecipes {
            get {
                return ResourceManager.GetString("btnViewSavedRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate TDEE.
        /// </summary>
        internal static string calculateTheTDEE {
            get {
                return ResourceManager.GetString("calculateTheTDEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation.
        /// </summary>
        internal static string calculation {
            get {
                return ResourceManager.GetString("calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calendar_background {
            get {
                object obj = ResourceManager.GetObject("calendar_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string completeGoal {
            get {
                return ResourceManager.GetString("completeGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make informed choices - get nutritional data on almost 900,000 products!.
        /// </summary>
        internal static string DBProduct_SetToolTip {
            get {
                return ResourceManager.GetString("DBProduct_SetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product database.
        /// </summary>
        internal static string DBProduct_Title {
            get {
                return ResourceManager.GetString("DBProduct_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over 2.3 million recipes - find exactly what you like!.
        /// </summary>
        internal static string DBRecipe_SetToolTip {
            get {
                return ResourceManager.GetString("DBRecipe_SetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe database.
        /// </summary>
        internal static string DBRecipe_Title {
            get {
                return ResourceManager.GetString("DBRecipe_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner.
        /// </summary>
        internal static string dinner {
            get {
                return ResourceManager.GetString("dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ＆ Password.
        /// </summary>
        internal static string EmailAndPass {
            get {
                return ResourceManager.GetString("EmailAndPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Error_1 {
            get {
                object obj = ResourceManager.GetObject("Error_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap food {
            get {
                object obj = ResourceManager.GetObject("food", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap invisible_pas {
            get {
                object obj = ResourceManager.GetObject("invisible_pas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate TDEE.
        /// </summary>
        internal static string label_CalculateTDEE {
            get {
                return ResourceManager.GetString("label_CalculateTDEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string label_City {
            get {
                return ResourceManager.GetString("label_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clarifai AI model will recognize the dishes and products in the photo, providing detailed information about their composition and TDEE. Control your diet easily and conveniently!.
        /// </summary>
        internal static string label_Clarifai {
            get {
                return ResourceManager.GetString("label_Clarifai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string label_ConfirmPassword {
            get {
                return ResourceManager.GetString("label_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string label_Country {
            get {
                return ResourceManager.GetString("label_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create goal.
        /// </summary>
        internal static string label_CreateGoal_h1 {
            get {
                return ResourceManager.GetString("label_CreateGoal_h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        internal static string label_CurrentPassword {
            get {
                return ResourceManager.GetString("label_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Result.
        /// </summary>
        internal static string label_CurrentResult {
            get {
                return ResourceManager.GetString("label_CurrentResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion Date.
        /// </summary>
        internal static string label_DateCompletion {
            get {
                return ResourceManager.GetString("label_DateCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        internal static string label_DateOfBirth {
            get {
                return ResourceManager.GetString("label_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string label_Email {
            get {
                return ResourceManager.GetString("label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ＆ Password.
        /// </summary>
        internal static string label_EmailPassword {
            get {
                return ResourceManager.GetString("label_EmailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Dish.
        /// </summary>
        internal static string label_FavoriteDish {
            get {
                return ResourceManager.GetString("label_FavoriteDish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string label_Female {
            get {
                return ResourceManager.GetString("label_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string label_FirstName {
            get {
                return ResourceManager.GetString("label_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri.
        /// </summary>
        internal static string label_Fri {
            get {
                return ResourceManager.GetString("label_Fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Information.
        /// </summary>
        internal static string label_GeneralInfo {
            get {
                return ResourceManager.GetString("label_GeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal.
        /// </summary>
        internal static string label_Goal {
            get {
                return ResourceManager.GetString("label_Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string label_GoalDescription {
            get {
                return ResourceManager.GetString("label_GoalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Progress.
        /// </summary>
        internal static string label_GoalProgress_h2 {
            get {
                return ResourceManager.GetString("label_GoalProgress_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals.
        /// </summary>
        internal static string label_Goals_h1 {
            get {
                return ResourceManager.GetString("label_Goals_h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health must always come first.
        /// </summary>
        internal static string label_HealthMessage_h2 {
            get {
                return ResourceManager.GetString("label_HealthMessage_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string label_Height {
            get {
                return ResourceManager.GetString("label_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string label_History {
            get {
                return ResourceManager.GetString("label_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrated Product and Recipe Database.
        /// </summary>
        internal static string label_IntegratedDB_h2 {
            get {
                return ResourceManager.GetString("label_IntegratedDB_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string label_LastName {
            get {
                return ResourceManager.GetString("label_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string label_Male {
            get {
                return ResourceManager.GetString("label_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the option to update your email address and password as needed..
        /// </summary>
        internal static string label_Message_h2 {
            get {
                return ResourceManager.GetString("label_Message_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        internal static string label_Mon {
            get {
                return ResourceManager.GetString("label_Mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Nutrition.
        /// </summary>
        internal static string label_MyNutrition {
            get {
                return ResourceManager.GetString("label_MyNutrition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Email.
        /// </summary>
        internal static string label_NewEmail {
            get {
                return ResourceManager.GetString("label_NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string label_NewPassword {
            get {
                return ResourceManager.GetString("label_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string label_Notes {
            get {
                return ResourceManager.GetString("label_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History not found.
        /// </summary>
        internal static string label_NotFound {
            get {
                return ResourceManager.GetString("label_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutrition .
        /// </summary>
        internal static string label_Nutrition_h2 {
            get {
                return ResourceManager.GetString("label_Nutrition_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        internal static string label_PersonalInformation {
            get {
                return ResourceManager.GetString("label_PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Activity.
        /// </summary>
        internal static string label_PhsActivity {
            get {
                return ResourceManager.GetString("label_PhsActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 900,000 Products.
        /// </summary>
        internal static string label_Products_h3 {
            get {
                return ResourceManager.GetString("label_Products_h3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Actions.
        /// </summary>
        internal static string label_QuickAction_h1 {
            get {
                return ResourceManager.GetString("label_QuickAction_h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.3M+ Recipes.
        /// </summary>
        internal static string label_Recipes_h3 {
            get {
                return ResourceManager.GetString("label_Recipes_h3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        internal static string label_Sat {
            get {
                return ResourceManager.GetString("label_Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Recipes.
        /// </summary>
        internal static string label_SavedRecipes_h2 {
            get {
                return ResourceManager.GetString("label_SavedRecipes_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        internal static string label_Sun {
            get {
                return ResourceManager.GetString("label_Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Result.
        /// </summary>
        internal static string label_TargetValue {
            get {
                return ResourceManager.GetString("label_TargetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Daily Energy.
        /// </summary>
        internal static string label_TDEE {
            get {
                return ResourceManager.GetString("label_TDEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu.
        /// </summary>
        internal static string label_Thu {
            get {
                return ResourceManager.GetString("label_Thu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tue.
        /// </summary>
        internal static string label_Tue {
            get {
                return ResourceManager.GetString("label_Tue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update progress.
        /// </summary>
        internal static string label_UpdateProgress {
            get {
                return ResourceManager.GetString("label_UpdateProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        internal static string label_Wed {
            get {
                return ResourceManager.GetString("label_Wed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string label_Weight {
            get {
                return ResourceManager.GetString("label_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon logo_2_Remove {
            get {
                object obj = ResourceManager.GetObject("logo_2_Remove", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_chatbot {
            get {
                object obj = ResourceManager.GetObject("logo_chatbot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logout {
            get {
                object obj = ResourceManager.GetObject("logout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch.
        /// </summary>
        internal static string lunch {
            get {
                return ResourceManager.GetString("lunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a message....
        /// </summary>
        internal static string messageFromUser {
            get {
                return ResourceManager.GetString("messageFromUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning.
        /// </summary>
        internal static string morning {
            get {
                return ResourceManager.GetString("morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        internal static string myProfile {
            get {
                return ResourceManager.GetString("myProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap name_bf_2 {
            get {
                object obj = ResourceManager.GetObject("name_bf_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newchat_active {
            get {
                object obj = ResourceManager.GetObject("newchat_active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newchat_hover {
            get {
                object obj = ResourceManager.GetObject("newchat_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newchat_inactive {
            get {
                object obj = ResourceManager.GetObject("newchat_inactive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nutrition_background {
            get {
                object obj = ResourceManager.GetObject("nutrition_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap password_hide {
            get {
                object obj = ResourceManager.GetObject("password_hide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap password_show {
            get {
                object obj = ResourceManager.GetObject("password_show", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        internal static string personalInfo {
            get {
                return ResourceManager.GetString("personalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pikachu_ChatBot {
            get {
                object obj = ResourceManager.GetObject("Pikachu_ChatBot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap product_not_found {
            get {
                object obj = ResourceManager.GetObject("product_not_found", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap products_background {
            get {
                object obj = ResourceManager.GetObject("products_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap recipes_background {
            get {
                object obj = ResourceManager.GetObject("recipes_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap remove_scanner {
            get {
                object obj = ResourceManager.GetObject("remove_scanner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap remove_scanner_hover {
            get {
                object obj = ResourceManager.GetObject("remove_scanner_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string saveEmPass {
            get {
                return ResourceManager.GetString("saveEmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save goal.
        /// </summary>
        internal static string saveGoal {
            get {
                return ResourceManager.GetString("saveGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_product {
            get {
                object obj = ResourceManager.GetObject("search_product", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_product_hover {
            get {
                object obj = ResourceManager.GetObject("search_product_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_recipes {
            get {
                object obj = ResourceManager.GetObject("search_recipes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_recipes_hover {
            get {
                object obj = ResourceManager.GetObject("search_recipes_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap send_active {
            get {
                object obj = ResourceManager.GetObject("send_active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap send_hover {
            get {
                object obj = ResourceManager.GetObject("send_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap send_inactive {
            get {
                object obj = ResourceManager.GetObject("send_inactive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Success_1 {
            get {
                object obj = ResourceManager.GetObject("Success_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        internal static string textSession {
            get {
                return ResourceManager.GetString("textSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close sidebar.
        /// </summary>
        internal static string toolTip_closeSidebar {
            get {
                return ResourceManager.GetString("toolTip_closeSidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed goals.
        /// </summary>
        internal static string toolTip_Competed_Title {
            get {
                return ResourceManager.GetString("toolTip_Competed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete photo.
        /// </summary>
        internal static string toolTip_delete {
            get {
                return ResourceManager.GetString("toolTip_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutrition goal for the day.
        /// </summary>
        internal static string toolTip_GoalNutrition {
            get {
                return ResourceManager.GetString("toolTip_GoalNutrition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of goals this month.
        /// </summary>
        internal static string toolTip_Goals {
            get {
                return ResourceManager.GetString("toolTip_Goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string toolTip_Goals_SetToolTip {
            get {
                return ResourceManager.GetString("toolTip_Goals_SetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string toolTip_languageEN {
            get {
                return ResourceManager.GetString("toolTip_languageEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        internal static string toolTip_languageUK {
            get {
                return ResourceManager.GetString("toolTip_languageUK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string toolTip_logout {
            get {
                return ResourceManager.GetString("toolTip_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New chat.
        /// </summary>
        internal static string toolTip_newChat {
            get {
                return ResourceManager.GetString("toolTip_newChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next month.
        /// </summary>
        internal static string toolTip_nextMonth {
            get {
                return ResourceManager.GetString("toolTip_nextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open sidebar.
        /// </summary>
        internal static string toolTip_openSidebar {
            get {
                return ResourceManager.GetString("toolTip_openSidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous month.
        /// </summary>
        internal static string toolTip_previousMonth {
            get {
                return ResourceManager.GetString("toolTip_previousMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot response time.
        /// </summary>
        internal static string toolTip_timer {
            get {
                return ResourceManager.GetString("toolTip_timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total goals.
        /// </summary>
        internal static string toolTip_TotalGoals_Title {
            get {
                return ResourceManager.GetString("toolTip_TotalGoals_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload photo.
        /// </summary>
        internal static string toolTip_uploadPhoto {
            get {
                return ResourceManager.GetString("toolTip_uploadPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string toolTip_Version {
            get {
                return ResourceManager.GetString("toolTip_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string updateProgress {
            get {
                return ResourceManager.GetString("updateProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update TDEE.
        /// </summary>
        internal static string updateTheTDEE {
            get {
                return ResourceManager.GetString("updateTheTDEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap upload_image {
            get {
                object obj = ResourceManager.GetObject("upload_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string upload_img {
            get {
                return ResourceManager.GetString("upload_img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Warning_1 {
            get {
                object obj = ResourceManager.GetObject("Warning_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
